stages:
    - verify
    - build
    - test

lint_frontend:
    image: node:10.6
    stage: verify
    script: cd frontend/ && npm install && npm run lint

build_app:
    stage: build
    script: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -V

run_tests:
    image: node:10.16
    stage: test
    script:
        - cd frontend/ && npm run test
        - ./mvnw verify -P skip-frontend-build,arquillian-wildfly-managed
    artifacts:
        paths:
            - target/CMD.waro


